//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keutmann.SharePointManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SPManagerLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPManagerLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Keutmann.SharePointManager.SPManagerLanguage", typeof(SPManagerLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration Service.
        /// </summary>
        internal static string AdministrationService {
            get {
                return ResourceManager.GetString("AdministrationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Collection.
        /// </summary>
        internal static string AlertCollection_Text {
            get {
                return ResourceManager.GetString("AlertCollection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlertCollection.
        /// </summary>
        internal static string AlertCollection_ToolTip {
            get {
                return ResourceManager.GetString("AlertCollection_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationPools.
        /// </summary>
        internal static string ApplicationPools_Text {
            get {
                return ResourceManager.GetString("ApplicationPools_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPApplicationPoolCollection.
        /// </summary>
        internal static string ApplicationPools_ToolTip {
            get {
                return ResourceManager.GetString("ApplicationPools_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Proxies.
        /// </summary>
        internal static string ApplicationProxes_Text {
            get {
                return ResourceManager.GetString("ApplicationProxes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Proxies.
        /// </summary>
        internal static string ApplicationProxes_ToolTip {
            get {
                return ResourceManager.GetString("ApplicationProxes_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup site.
        /// </summary>
        internal static string BackupSite_Text {
            get {
                return ResourceManager.GetString("BackupSite_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string Browser_Text {
            get {
                return ResourceManager.GetString("Browser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel all modifications.
        /// </summary>
        internal static string Cancel_All_Modifications {
            get {
                return ResourceManager.GetString("Cancel_All_Modifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes is saved.
        /// </summary>
        internal static string Changes_Saved {
            get {
                return ResourceManager.GetString("Changes_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Service.
        /// </summary>
        internal static string ContentService {
            get {
                return ResourceManager.GetString("ContentService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentTypes.
        /// </summary>
        internal static string ContentTypes_Text {
            get {
                return ResourceManager.GetString("ContentTypes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentType Collection.
        /// </summary>
        internal static string ContentTypes_ToolTip {
            get {
                return ResourceManager.GetString("ContentTypes_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usages.
        /// </summary>
        internal static string ContentTypeUsages_Text {
            get {
                return ResourceManager.GetString("ContentTypeUsages_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows where the contenttype is being used..
        /// </summary>
        internal static string ContentTypeUsages_ToolTip {
            get {
                return ResourceManager.GetString("ContentTypeUsages_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy_Text {
            get {
                return ResourceManager.GetString("Copy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Cut_Text {
            get {
                return ResourceManager.GetString("Cut_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete_Text {
            get {
                return ResourceManager.GetString("Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do not exist..
        /// </summary>
        internal static string Do_Not_Exist {
            get {
                return ResourceManager.GetString("Do_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Receivers.
        /// </summary>
        internal static string EventReceiverDefinitionCollection_Text {
            get {
                return ResourceManager.GetString("EventReceiverDefinitionCollection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Receiver Definition Collection.
        /// </summary>
        internal static string EventReceiverDefinitionCollection_ToolTip {
            get {
                return ResourceManager.GetString("EventReceiverDefinitionCollection_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, not able to update data..
        /// </summary>
        internal static string ExplorerBase_Error {
            get {
                return ResourceManager.GetString("ExplorerBase_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string Feature_Activate {
            get {
                return ResourceManager.GetString("Feature_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string Feature_Deactivate {
            get {
                return ResourceManager.GetString("Feature_Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition unknown.
        /// </summary>
        internal static string Feature_Message01 {
            get {
                return ResourceManager.GetString("Feature_Message01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No feature definition object defined!.
        /// </summary>
        internal static string Feature_Message02 {
            get {
                return ResourceManager.GetString("Feature_Message02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string FeatureDefinition_Install {
            get {
                return ResourceManager.GetString("FeatureDefinition_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not installed).
        /// </summary>
        internal static string FeatureDefinition_Message01 {
            get {
                return ResourceManager.GetString("FeatureDefinition_Message01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string FeatureDefinition_Uninstall {
            get {
                return ResourceManager.GetString("FeatureDefinition_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features Definitions.
        /// </summary>
        internal static string FeaturesDefinitions_Text {
            get {
                return ResourceManager.GetString("FeaturesDefinitions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features Definitions.
        /// </summary>
        internal static string FeaturesDefinitions_ToolTip {
            get {
                return ResourceManager.GetString("FeaturesDefinitions_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        internal static string Fields_Text {
            get {
                return ResourceManager.GetString("Fields_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Collection.
        /// </summary>
        internal static string Fields_ToolTip {
            get {
                return ResourceManager.GetString("Fields_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string File_Item {
            get {
                return ResourceManager.GetString("File_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        internal static string Forms_Text {
            get {
                return ResourceManager.GetString("Forms_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Collection.
        /// </summary>
        internal static string Forms_ToolTip {
            get {
                return ResourceManager.GetString("Forms_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid View.
        /// </summary>
        internal static string GridView_List {
            get {
                return ResourceManager.GetString("GridView_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridView.
        /// </summary>
        internal static string GridView_Text {
            get {
                return ResourceManager.GetString("GridView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Settings.
        /// </summary>
        internal static string IisSettings_Text {
            get {
                return ResourceManager.GetString("IisSettings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Settings Collection.
        /// </summary>
        internal static string IisSettings_ToolTip {
            get {
                return ResourceManager.GetString("IisSettings_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include sub folders.
        /// </summary>
        internal static string Include_Sub__Folders {
            get {
                return ResourceManager.GetString("Include_Sub _Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include sub sites.
        /// </summary>
        internal static string Include_Sub_Sites {
            get {
                return ResourceManager.GetString("Include_Sub_Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Interface_About {
            get {
                return ResourceManager.GetString("Interface_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Interface_About_Text {
            get {
                return ResourceManager.GetString("Interface_About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About SharePoint Manager 2007.
        /// </summary>
        internal static string Interface_About_ToolTip {
            get {
                return ResourceManager.GetString("Interface_About_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string Interface_ButtonCancel {
            get {
                return ResourceManager.GetString("Interface_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string Interface_ButtonOK {
            get {
                return ResourceManager.GetString("Interface_ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string Interface_Cancel_Text {
            get {
                return ResourceManager.GetString("Interface_Cancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel all changes.
        /// </summary>
        internal static string Interface_Cancel_ToolTip {
            get {
                return ResourceManager.GetString("Interface_Cancel_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to a  SharePoint Configuration Database.
        /// </summary>
        internal static string Interface_ConnectToSP {
            get {
                return ResourceManager.GetString("Interface_ConnectToSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        internal static string Interface_DutchLanguage {
            get {
                return ResourceManager.GetString("Interface_DutchLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string Interface_Edit_Text {
            get {
                return ResourceManager.GetString("Interface_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Interface_Edit_ToolTip {
            get {
                return ResourceManager.GetString("Interface_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Interface_EnglishLanguage {
            get {
                return ResourceManager.GetString("Interface_EnglishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter configuration database name:.
        /// </summary>
        internal static string Interface_EnterConfigDB {
            get {
                return ResourceManager.GetString("Interface_EnterConfigDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter information to connect to a SharePoint Configuration Database..
        /// </summary>
        internal static string Interface_EnterInfo_Text {
            get {
                return ResourceManager.GetString("Interface_EnterInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        internal static string Interface_Exit_Text {
            get {
                return ResourceManager.GetString("Interface_Exit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close program.
        /// </summary>
        internal static string Interface_Exit_ToolTip {
            get {
                return ResourceManager.GetString("Interface_Exit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string Interface_File_Text {
            get {
                return ResourceManager.GetString("Interface_File_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Interface_File_ToolTip {
            get {
                return ResourceManager.GetString("Interface_File_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Full.
        /// </summary>
        internal static string Interface_Full_Text {
            get {
                return ResourceManager.GetString("Interface_Full_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Interface_Full_ToolTip {
            get {
                return ResourceManager.GetString("Interface_Full_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string Interface_Help_Text {
            get {
                return ResourceManager.GetString("Interface_Help_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Interface_Help_ToolTip {
            get {
                return ResourceManager.GetString("Interface_Help_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string Interface_Languages_Text {
            get {
                return ResourceManager.GetString("Interface_Languages_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Interface_Languages_ToolTip {
            get {
                return ResourceManager.GetString("Interface_Languages_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on to the server.
        /// </summary>
        internal static string Interface_LogOn {
            get {
                return ResourceManager.GetString("Interface_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me&amp;dium.
        /// </summary>
        internal static string Interface_Medium_Text {
            get {
                return ResourceManager.GetString("Interface_Medium_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Interface_Medium_ToolTip {
            get {
                return ResourceManager.GetString("Interface_Medium_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Minimal.
        /// </summary>
        internal static string Interface_Minimal_Text {
            get {
                return ResourceManager.GetString("Interface_Minimal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Interface_Minimal_ToolTip {
            get {
                return ResourceManager.GetString("Interface_Minimal_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Model.
        /// </summary>
        internal static string Interface_ObjectModel_Text {
            get {
                return ResourceManager.GetString("Interface_ObjectModel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Interface_ObjectModel_ToolTip {
            get {
                return ResourceManager.GetString("Interface_ObjectModel_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Interface_Ok {
            get {
                return ResourceManager.GetString("Interface_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Connection.
        /// </summary>
        internal static string Interface_OpenConn {
            get {
                return ResourceManager.GetString("Interface_OpenConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Database.
        /// </summary>
        internal static string Interface_OpenDatabase_Text {
            get {
                return ResourceManager.GetString("Interface_OpenDatabase_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Database.
        /// </summary>
        internal static string Interface_OpenDatabase_ToolTip {
            get {
                return ResourceManager.GetString("Interface_OpenDatabase_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Database Connection.
        /// </summary>
        internal static string Interface_OpenDataBaseConn_Text {
            get {
                return ResourceManager.GetString("Interface_OpenDataBaseConn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Interface_OpenDataBaseConn_ToolTip {
            get {
                return ResourceManager.GetString("Interface_OpenDataBaseConn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Interface_Password {
            get {
                return ResourceManager.GetString("Interface_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Interface_Refresh_Text {
            get {
                return ResourceManager.GetString("Interface_Refresh_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Interface_Refresh_ToolTip {
            get {
                return ResourceManager.GetString("Interface_Refresh_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh current node.
        /// </summary>
        internal static string Interface_RefreshNode_Text {
            get {
                return ResourceManager.GetString("Interface_RefreshNode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Interface_RefreshNode_ToolTip {
            get {
                return ResourceManager.GetString("Interface_RefreshNode_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string Interface_Save_Text {
            get {
                return ResourceManager.GetString("Interface_Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to SharePoint.
        /// </summary>
        internal static string Interface_Save_ToolTip {
            get {
                return ResourceManager.GetString("Interface_Save_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;all.
        /// </summary>
        internal static string Interface_SaveAll_Text {
            get {
                return ResourceManager.GetString("Interface_SaveAll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all changes to SharePoint.
        /// </summary>
        internal static string Interface_SaveAll_ToolTip {
            get {
                return ResourceManager.GetString("Interface_SaveAll_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name.
        /// </summary>
        internal static string Interface_ServerName {
            get {
                return ResourceManager.GetString("Interface_ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Interface_Settings_Text {
            get {
                return ResourceManager.GetString("Interface_Settings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Interface_Settings_ToolTip {
            get {
                return ResourceManager.GetString("Interface_Settings_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand nodes on startup (Shallow mode).
        /// </summary>
        internal static string Interface_ShallowExpand {
            get {
                return ResourceManager.GetString("Interface_ShallowExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string Interface_SpanishLanguage {
            get {
                return ResourceManager.GetString("Interface_SpanishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Bar.
        /// </summary>
        internal static string Interface_StatusBar_Text {
            get {
                return ResourceManager.GetString("Interface_StatusBar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Interface_StatusBar_ToolTip {
            get {
                return ResourceManager.GetString("Interface_StatusBar_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        internal static string Interface_SwedishLanguage {
            get {
                return ResourceManager.GetString("Interface_SwedishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Test Connection.
        /// </summary>
        internal static string Interface_TestConn {
            get {
                return ResourceManager.GetString("Interface_TestConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Bar.
        /// </summary>
        internal static string Interface_ToolBar_Text {
            get {
                return ResourceManager.GetString("Interface_ToolBar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Interface_ToolBar_ToolTip {
            get {
                return ResourceManager.GetString("Interface_ToolBar_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        internal static string Interface_UserName {
            get {
                return ResourceManager.GetString("Interface_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SQL Server Authentication.
        /// </summary>
        internal static string Interface_UseSQLServerAuth {
            get {
                return ResourceManager.GetString("Interface_UseSQLServerAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows Authentication.
        /// </summary>
        internal static string Interface_UseWindowsAuth {
            get {
                return ResourceManager.GetString("Interface_UseWindowsAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string Interface_View_Text {
            get {
                return ResourceManager.GetString("Interface_View_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Interface_View_ToolTip {
            get {
                return ResourceManager.GetString("Interface_View_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Manager 2007\nVer: 0.31.7.0127\n\nCreated by\nCarsten Keutmann\n\ncarsten@keutmann.dk.
        /// </summary>
        internal static string Intervace_About_Text {
            get {
                return ResourceManager.GetString("Intervace_About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Items_Text {
            get {
                return ResourceManager.GetString("Items_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Items_ToolTip {
            get {
                return ResourceManager.GetString("Items_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPJobDefinitionCollection.
        /// </summary>
        internal static string JobDefinitionCollection_ToolTip {
            get {
                return ResourceManager.GetString("JobDefinitionCollection_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Definitions.
        /// </summary>
        internal static string JobDefinitions_Text {
            get {
                return ResourceManager.GetString("JobDefinitions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Item Collection.
        /// </summary>
        internal static string ListItemCollection {
            get {
                return ResourceManager.GetString("ListItemCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        internal static string Lists_Text {
            get {
                return ResourceManager.GetString("Lists_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Lists_ToolTip {
            get {
                return ResourceManager.GetString("Lists_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Templates.
        /// </summary>
        internal static string ListTemplates_Text {
            get {
                return ResourceManager.GetString("ListTemplates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading field columns.
        /// </summary>
        internal static string LoadingFieldColumns {
            get {
                return ResourceManager.GetString("LoadingFieldColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure you want to delete this item?.
        /// </summary>
        internal static string Message_DeleteWarning {
            get {
                return ResourceManager.GetString("Message_DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Paste_Text {
            get {
                return ResourceManager.GetString("Paste_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties_Text {
            get {
                return ResourceManager.GetString("Properties_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties_ToolTip {
            get {
                return ResourceManager.GetString("Properties_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Bag.
        /// </summary>
        internal static string PropertyBag_Text {
            get {
                return ResourceManager.GetString("PropertyBag_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Bag.
        /// </summary>
        internal static string PropertyBag_ToolTip {
            get {
                return ResourceManager.GetString("PropertyBag_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota Template.
        /// </summary>
        internal static string QuotaTemplate_Text {
            get {
                return ResourceManager.GetString("QuotaTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPQuotaTemplate.
        /// </summary>
        internal static string QuotaTemplate_ToolTip {
            get {
                return ResourceManager.GetString("QuotaTemplate_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPQuotaTemplateCollection.
        /// </summary>
        internal static string QuotaTemplateCollection_ToolTip {
            get {
                return ResourceManager.GetString("QuotaTemplateCollection_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuotaTemplates.
        /// </summary>
        internal static string QuotaTemplatesCollection_Text {
            get {
                return ResourceManager.GetString("QuotaTemplatesCollection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle.
        /// </summary>
        internal static string Recycle {
            get {
                return ResourceManager.GetString("Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecycleBin.
        /// </summary>
        internal static string RecycleBin_Text {
            get {
                return ResourceManager.GetString("RecycleBin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle Bin.
        /// </summary>
        internal static string RecycleBin_ToolTip {
            get {
                return ResourceManager.GetString("RecycleBin_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh_Text {
            get {
                return ResourceManager.GetString("Refresh_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore All.
        /// </summary>
        internal static string RestoreAll {
            get {
                return ResourceManager.GetString("RestoreAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running jobs.
        /// </summary>
        internal static string RunningJobs_Text {
            get {
                return ResourceManager.GetString("RunningJobs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Job Collection.
        /// </summary>
        internal static string RunningJobs_ToolTip {
            get {
                return ResourceManager.GetString("RunningJobs_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving changes to SharePoint.
        /// </summary>
        internal static string Saving__Changes {
            get {
                return ResourceManager.GetString("Saving _Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving all changes to SharePoint.
        /// </summary>
        internal static string Saving_All_Changes {
            get {
                return ResourceManager.GetString("Saving_All_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        internal static string Servers_Text {
            get {
                return ResourceManager.GetString("Servers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        internal static string Servers_ToolTip {
            get {
                return ResourceManager.GetString("Servers_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Proxies.
        /// </summary>
        internal static string ServiceProxies_Text {
            get {
                return ResourceManager.GetString("ServiceProxies_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Proxies.
        /// </summary>
        internal static string ServiceProxies_ToolTip {
            get {
                return ResourceManager.GetString("ServiceProxies_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services_Text {
            get {
                return ResourceManager.GetString("Services_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Collection.
        /// </summary>
        internal static string Services_ToolTip {
            get {
                return ResourceManager.GetString("Services_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Collection.
        /// </summary>
        internal static string SiteCollection_Site_ToolTip {
            get {
                return ResourceManager.GetString("SiteCollection_Site_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Collection.
        /// </summary>
        internal static string SiteCollection_SiteCollection_Text {
            get {
                return ResourceManager.GetString("SiteCollection_SiteCollection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPSiteCollection.
        /// </summary>
        internal static string SiteCollection_SiteCollection_ToolTip {
            get {
                return ResourceManager.GetString("SiteCollection_SiteCollection_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Features.
        /// </summary>
        internal static string SiteFeatures_Text {
            get {
                return ResourceManager.GetString("SiteFeatures_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Feature Collection.
        /// </summary>
        internal static string SiteFeatures_ToolTip {
            get {
                return ResourceManager.GetString("SiteFeatures_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Subscriptions.
        /// </summary>
        internal static string SiteSubscriptionCollection_Text {
            get {
                return ResourceManager.GetString("SiteSubscriptionCollection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Subscriptions.
        /// </summary>
        internal static string SiteSubscriptionCollection_ToolTip {
            get {
                return ResourceManager.GetString("SiteSubscriptionCollection_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions.
        /// </summary>
        internal static string Solutions_Text {
            get {
                return ResourceManager.GetString("Solutions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions.
        /// </summary>
        internal static string Solutions_ToolTip {
            get {
                return ResourceManager.GetString("Solutions_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a site url..
        /// </summary>
        internal static string Specify_Site_Url {
            get {
                return ResourceManager.GetString("Specify_Site_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succes!.
        /// </summary>
        internal static string Succes {
            get {
                return ResourceManager.GetString("Succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks_Text {
            get {
                return ResourceManager.GetString("Tasks_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing database connection.
        /// </summary>
        internal static string Testing_Database_Connection {
            get {
                return ResourceManager.GetString("Testing_Database_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text_Text {
            get {
                return ResourceManager.GetString("Text_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file.
        /// </summary>
        internal static string The_File {
            get {
                return ResourceManager.GetString("The_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users_Text {
            get {
                return ResourceManager.GetString("Users_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Collection.
        /// </summary>
        internal static string Users_ToolTip {
            get {
                return ResourceManager.GetString("Users_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Collection.
        /// </summary>
        internal static string UserSolutionCollection_Text {
            get {
                return ResourceManager.GetString("UserSolutionCollection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Solution Collection.
        /// </summary>
        internal static string UserSolutionCollection_ToolTip {
            get {
                return ResourceManager.GetString("UserSolutionCollection_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version History.
        /// </summary>
        internal static string VersionHistory_File_Text {
            get {
                return ResourceManager.GetString("VersionHistory_File_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version History Collection.
        /// </summary>
        internal static string VersionHistory_File_ToolTip {
            get {
                return ResourceManager.GetString("VersionHistory_File_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version History.
        /// </summary>
        internal static string VersionHistory_ListItem_Text {
            get {
                return ResourceManager.GetString("VersionHistory_ListItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version History Collection.
        /// </summary>
        internal static string VersionHistory_ListItem_ToolTip {
            get {
                return ResourceManager.GetString("VersionHistory_ListItem_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPView.
        /// </summary>
        internal static string View_ToolTip {
            get {
                return ResourceManager.GetString("View_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Default).
        /// </summary>
        internal static string ViewNode_Message01 {
            get {
                return ResourceManager.GetString("ViewNode_Message01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string ViewsCollection_Text {
            get {
                return ResourceManager.GetString("ViewsCollection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Collection.
        /// </summary>
        internal static string ViewsCollection_ToolTip {
            get {
                return ResourceManager.GetString("ViewsCollection_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Application.
        /// </summary>
        internal static string WebApplication_ToolTip {
            get {
                return ResourceManager.GetString("WebApplication_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webapplication Features.
        /// </summary>
        internal static string WebApplicationFeatures_Text {
            get {
                return ResourceManager.GetString("WebApplicationFeatures_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webapplication Feature Collection.
        /// </summary>
        internal static string WebApplicationFeatures_ToolTip {
            get {
                return ResourceManager.GetString("WebApplicationFeatures_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Applications.
        /// </summary>
        internal static string WebApplications_Text {
            get {
                return ResourceManager.GetString("WebApplications_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Application Collection.
        /// </summary>
        internal static string WebApplications_ToolTip {
            get {
                return ResourceManager.GetString("WebApplications_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Features.
        /// </summary>
        internal static string WebFeatures_Text {
            get {
                return ResourceManager.GetString("WebFeatures_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Feature Collection.
        /// </summary>
        internal static string WebFeatures_ToolTip {
            get {
                return ResourceManager.GetString("WebFeatures_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebParts.
        /// </summary>
        internal static string WebParts_Text {
            get {
                return ResourceManager.GetString("WebParts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebPart Collection.
        /// </summary>
        internal static string WebParts_ToolTip {
            get {
                return ResourceManager.GetString("WebParts_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webs.
        /// </summary>
        internal static string Webs_Text {
            get {
                return ResourceManager.GetString("Webs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Collection.
        /// </summary>
        internal static string Webs_ToolTip {
            get {
                return ResourceManager.GetString("Webs_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Associations.
        /// </summary>
        internal static string WorkflowAssociations_Text {
            get {
                return ResourceManager.GetString("WorkflowAssociations_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Associations.
        /// </summary>
        internal static string WorkflowAssociations_ToolTip {
            get {
                return ResourceManager.GetString("WorkflowAssociations_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter the workflow at certain points while it is running on an item.
        /// </summary>
        internal static string WorkflowModification_ToolTip {
            get {
                return ResourceManager.GetString("WorkflowModification_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Modifications.
        /// </summary>
        internal static string WorkflowModifications_Text {
            get {
                return ResourceManager.GetString("WorkflowModifications_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter the workflow at certain points while it is running on an item.
        /// </summary>
        internal static string WorkflowModifications_ToolTip {
            get {
                return ResourceManager.GetString("WorkflowModifications_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflows.
        /// </summary>
        internal static string Workflows_Text {
            get {
                return ResourceManager.GetString("Workflows_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflows.
        /// </summary>
        internal static string Workflows_ToolTip {
            get {
                return ResourceManager.GetString("Workflows_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflows Tasks.
        /// </summary>
        internal static string WorkflowsTasks_Text {
            get {
                return ResourceManager.GetString("WorkflowsTasks_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflows Task Collection.
        /// </summary>
        internal static string WorkflowsTasks_ToolTip {
            get {
                return ResourceManager.GetString("WorkflowsTasks_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml.
        /// </summary>
        internal static string Xml_Text {
            get {
                return ResourceManager.GetString("Xml_Text", resourceCulture);
            }
        }
    }
}
